---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  labels:
    app: localstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      serviceAccountName: localstack
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: docker
        image: docker:latest
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        volumeMounts:
        - name: docker
          mountPath: "/var/run/docker.sock"
          subPath: "docker.sock"
      - name: localstack
        image: localstack/localstack
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        ports:
        - name: http
          containerPort: 8080
        - name: http-edge
          containerPort: 4566
        - name: http-backend
          containerPort: 4571
        env:
        - name: LOCALSTACK_API_KEY
          value: "4GUYapOrkD"
        - name: PORT_WEB_UI
          value: "8080"
        - name: HOST_TMP_FOLDER
          value: "/tmp/localstack"
        - name: DATA_DIR
          value: "/tmp/localstack/data"
        - name: DOCKER_HOST
          value: "unix:///var/run/docker.sock"
        - name: SERVICES
          value: "sts,stepfunctions,sqs,accessanalyzer,account,acm,acm-pca,alexaforbusiness,amp,amplify,amplifybackend,apigateway,apigatewaymanagementapi,apigatewayv2,appconfig,appconfigdata,appflow,appintegrations,application-autoscaling,application-insights,applicationcostprofiler,appmesh,apprunner,appstream,appsync,athena,auditmanager,autoscaling,autoscaling-plans,backup,batch,braket,budgets,ce,chime,chime-sdk-identity,chime-sdk-meetings,chime-sdk-messaging,cloud9,cloudcontrol,clouddirectory,cloudformation,cloudfront,cloudhsm,cloudhsmv2,cloudsearch,cloudsearchdomain,cloudtrail,cloudwatch,codeartifact,codebuild,codecommit,codeguru-reviewer,codeguruprofiler,codepipeline,codestar,codestar-connections,codestar-notifications,cognito-identity,cognito-idp,cognito-sync,comprehend,comprehendmedical,compute-optimizer,configservice,configure,connect,connect-contact-lens,connectparticipant,cur,customer-profiles,databrew,dataexchange,datapipeline,datasync,dax,deploy,detective,devicefarm,devops-guru,directconnect,discovery,dlm,dms,docdb,drs,ds,dynamodb,dynamodbstreams,ebs,ec2,ec2-instance-connect,ecr,ecr-public,ecs,efs,eks,elastic-inference,elasticache,elasticbeanstalk,elastictranscoder,elb,elbv2,emr,emr-containers,es,events,finspace,finspace-data,firehose,fis,fms,forecast,forecastquery,frauddetector,fsx,gamelift,glacier,globalaccelerator,glue,grafana,greengrass,greengrassv2,groundstation,guardduty,health,healthlake,history,honeycode,iam,identitystore,imagebuilder,importexport,inspector,iot,iot-data,iot-jobs-data,iot1click-devices,iot1click-projects,iotanalytics,iotdeviceadvisor,iotevents,iotevents-data,iotfleethub,iotsecuretunneling,iotsitewise,iotthingsgraph,iotwireless,ivs,kafka,kafkaconnect,kendra,kinesis,kinesis-video-archived-media,kinesis-video-media,kinesis-video-signaling,kinesisanalytics,kinesisanalyticsv2,kinesisvideo,kms,lakeformation,lambda,lex-models,lex-runtime,lexv2-models,lexv2-runtime,license-manager,lightsail,location,logs,lookoutequipment,lookoutmetrics,lookoutvision,machinelearning,macie,macie2,managedblockchain,marketplace-catalog,marketplace-entitlement,marketplacecommerceanalytics,mediaconnect,mediaconvert,medialive,mediapackage,mediapackage-vod,mediastore,mediastore-data,mediatailor,memorydb,meteringmarketplace,mgh,mgn,migrationhub-config,migrationhubstrategy,mobile,mq,mturk,mwaa,neptune,network-firewall,networkmanager,nimble,opensearch,opsworks,opsworks-cm,organizations,outposts,panorama,personalize,personalize-events,personalize-runtime,pi,pinpoint,pinpoint-email,pinpoint-sms-voice,polly,pricing,proton,qldb,qldb-session,quicksight,ram,rds,rds-data,redshift,redshift-data,rekognition,resiliencehub,resource-groups,resourcegroupstaggingapi,robomaker,route53,route53-recovery-cluster,route53-recovery-control-config,route53-recovery-readiness,route53domains,route53resolver,s3,s3api,s3control,s3outposts,sagemaker,sagemaker-a2i-runtime,sagemaker-edge,sagemaker-featurestore-runtime,sagemaker-runtime,savingsplans,schemas,sdb,secretsmanager,securityhub,serverless,serverlessrepo,service-quotas,servicecatalog,servicecatalog-appregistry,servicediscovery,ses,sesv2,shield,signer,sms,snow-device-management,snowball,sns,ssm,ssm-contacts,ssm-incidents,sso,sso-admin,sso-oidc,storagegateway,sts,support,swf,synthetics,textract,timestream-query,timestream-write,transcribe,transfer,translate,voice-id,waf,waf-regional,wafv2,wellarchitected,wisdom,workdocs,worklink,workmail,workmailmessageflow,workspaces,xray"
        - name: DEBUG
          value: "1"
        - name: EDGE_PORT
          value: "4566"
        - name: LAMBDA_EXECUTOR
          value: "docker"
        volumeMounts:
        - name: data
          mountPath: "/tmp/localstack"
          subPath: "localstack"
        - name: docker
          mountPath: "/var/run/docker.sock"
          subPath: "docker.sock"
      volumes:
      - name: data
        emptyDir: {}
      - name: docker
        emptyDir: {}
