---
apiVersion: v1
kind: Service
metadata:
  name: localstack
spec:
  type: ClusterIP
  ports:
  - name: "http-edge"
    port: 4566
  - name: "http"
    port: 8080
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: localstack
spec:
  routes:
  - match: Host(`localstack.local`)
    kind: Rule
    services:
    - name: localstack
      port: 4566
  - match: Host(`localstack.local`) && Path(`/admin`)"
    kind: Rule
    services:
    - name: localstack
      port: 8080
