---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux         # ensures secret is generated in the right namespace                            
resources:
- https://github.com/fluxcd/helm-operator//deploy?ref=master
patchesJSON6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: helm-operator
    namespace: flux
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/args
      value:
      - --enabled-helm-versions=v3    
